//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDataFirstTAsk
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherCourse
    {
        public int TeacherCourseId { get; set; }
        public Nullable<int> TeacherId { get; set; }
        public Nullable<int> CourseId { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
